baseURL = "/"
languageCode = "zh-tw"
title = "Chang,Jui-Che / 張瑞哲"
theme = "papermod"

[pagination]
  pagerSize = 20

[params]
  env = "production"
  title = "Chang,Jui-Che / 張瑞哲"
  description = "Artist Portfolio"
  keywords = ["art", "portfolio", "installation", "contemporary art"]

  disableThemeToggle = false
  defaultTheme = "auto"
  ShowReadingTime = false
  ShowWordCount = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  disableScrollToTop = false
  hideFooter = false

  disableLanguageSwitchingButton = true

  [params.assets]
    customCSS = ["css/custom.css"]
